Layout/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Max: 27
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/PerceivedComplexity:
  Max: 8
Style/ClassAndModuleChildren:
  Enabled: false